# картинки для экскурсий

images1 = [
    "AgACAgIAAxkBAAIWD2VO2DK-hPH3-xaPtLsPYmLO664oAAJF1DEbdPV5SmL0alkQrbmxAQADAgADeAADMwQ",
    "AgACAgIAAxkBAAIWEGVO2FY1k_22dUynh2NiZc0zaxByAAJG1DEbdPV5Sogx_ovZs7KZAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWEWVO2I69bsoyWJ6RZ9brh_vN_kAtAAJH1DEbdPV5SuT4RRVq5LWrAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWEmVO2MMcYjiJUKYGCvHyr2P9YHSyAAJI1DEbdPV5Slatl2eFGUnOAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWE2VO2OCCBRq0Vn7CzMe08h2SHQ--AAJJ1DEbdPV5SsT-vVrc9zumAQADAgADeAADMwQ",
    "",
    "AgACAgIAAxkBAAIWFGVO2RX_l3Zje8CUD3rMS7TWItkkAAJK1DEbdPV5SokmKG3puGa_AQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWFWVO2TG2DlvkwYyCIMWrdGUc5fWuAAJL1DEbdPV5SlnKxjPfo-d8AQADAgADeAADMwQ",
    "",
    "AgACAgIAAxkBAAIWFmVO2VpBDDpp_haLclmi8hleh_wFAAJN1DEbdPV5SovIjFKhVNkHAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWF2VO2ZOyjhwiDJ5CQfCiJprnyAx4AAJX1DEbdPV5SsSr_7SSTHqGAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWGGVO2cxNfs0R197adApRz0qX1wAB-AACWNQxG3T1eUpZEVm5k7PPewEAAwIAA20AAzME",
    "",
    "AgACAgIAAxkBAAIWGWVO2fVcQSxlp-o8BYTcDWUwyhBLAAJZ1DEbdPV5Sr36-IN_xAJ8AQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWGmVO2ieMX3qWBZIctH4sT8xZQdDYAAJa1DEbdPV5SlA90-YIH84RAQADAgADeQADMwQ",
    ""
]

images2 = [
    "AgACAgIAAxkBAAIWG2VO26UrqaWoFyXkJgWjqst-RBV5AAJe1DEbdPV5SskzDRXr9ebeAQADAgADeAADMwQ",
    "AgACAgIAAxkBAAIWHGVO271nkKikP_v6JtgmSB0ffyvAAAJf1DEbdPV5StjgKToUgCnTAQADAgADeAADMwQ",
    "",
    "AgACAgIAAxkBAAIWLWVO3E0JK5zx4C5vMNVcEFlGwo3PAAJg1DEbdPV5SplVVbe1UrC9AQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWLmVO3HmqG_H7D4pw0zfImMA_euCTAAJh1DEbdPV5SgtfM_G-aFvRAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWL2VO3K1OBm8p2czA6ilK8ZxzSDgLAAJi1DEbdPV5SvZ3sh-GMSG2AQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWMGVO3MwHgOQSrMJxAAHSW_G-SPBTzwACY9QxG3T1eUru1vi9XQwr_QEAAwIAA3gAAzME",
    "",
    "AgACAgIAAxkBAAIWMWVO3P72qA6HTNVAT30VyQtSN7zsAAJk1DEbdPV5Svueg3m_ZqqGAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWMmVO3Tq4Oap_AebOO6q9jnZeierFAAJl1DEbdPV5SiwZoUTZIS8hAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWM2VO3W4bP_Nq3YmAAxfrkmJF0BkXAAJn1DEbdPV5SqET6igmJVyEAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWNGVO3Z2Kpt686rYM4JCdA9Y1pCTcAAJo1DEbdPV5SgFHdCJaUVtiAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWNmVO3coEJgABEH0ONNmFNWlaoQ21pAACa9QxG3T1eUo5Md2XbwsLFgEAAwIAA3kAAzME",
    "AgACAgIAAxkBAAIWN2VO3e2mkbTKv8QwnJeedSbqYyB8AAJs1DEbdPV5StWQaLZwEQQvAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWOGVO3iiIKJsp9pFPq3wqLjix5V2nAAJt1DEbdPV5SpdFo5YaSYpkAQADAgADeQADMwQ",
    "AgACAgIAAxkBAAIWOWVO3m6951gDTDjwFJBYXm4pZCpIAAJu1DEbdPV5SmydbjnbX2FsAQADAgADeQADMwQ",
    "",
    "AgACAgIAAxkBAAIWOmVO3pf_yluJ2Qxbp-aDOUGpvM4BAAJv1DEbdPV5SuF31QqBrINIAQADAgADeQADMwQ"
]

images3 = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]
